branches:
  only: 
    - master

matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode10.2
      script:
        # macOS
        - xcodebuild clean -project "Baconian.xcodeproj" 
        - xcodebuild test -project "Baconian.xcodeproj" -scheme "Baconian-macOS" -destination "platform=OS X" -configuration Debug

        # iOS
        - xcodebuild clean -project "Baconian.xcodeproj" 
        - xcodebuild test -project "Baconian.xcodeproj" -scheme "Baconian-iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X" -configuration Debug
