matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode12
      before_install:
        - pod repo update
      script:
        # macOS
        - xcodebuild clean -workspace "Baconian.xcworkspace" -scheme "Baconian-macOS"
        - xcodebuild test -workspace "Baconian.xcworkspace" -scheme "Baconian-macOS" -destination "platform=OS X" -configuration Debug

        # iOS
        - xcodebuild clean -workspace "Baconian.xcworkspace" -scheme "Baconian-iOS"
        - xcodebuild test -workspace "Baconian.xcworkspace" -scheme "Baconian-iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11 Pro Max" -configuration Debug
